name: CI/CD Deploy

on:
  push:
    branches:
      - testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Docker Hub login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push image (Docker handles build)
      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/snaplink-ui
          BRANCH=${{ github.ref_name }}
          SHA=${{ github.sha }}

          docker build -f DockerFile \
            -t $IMAGE:latest \
            -t $IMAGE:$BRANCH \
            -t $IMAGE:$BRANCH-$SHA .
            
          docker push $IMAGE:latest
          docker push $IMAGE:$BRANCH-$SHA

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/snaplink-ui

            docker pull $IMAGE:latest
            docker stop snaplink-ui || true
            docker rm snaplink-ui || true

            docker run -d \
              --restart unless-stopped \
              -p 80:80 \
              --name snaplink-ui \
              $IMAGE:latest
